### PR TITLE
Use floating filter to make filtering more visible

### LINKED ISSUE #16: Add floating filter header
Screenshot 2024-05-02 at 1 32 32 PM

### PR DESCRIPTION
**Pull request by juberti**
Fixes #16 (see bug for screenshot)

### CODE REVIEW

**Review by benlower — CHANGES_REQUESTED** [review]
this looks pretty good but it's not obv to me what the "search" boxes are doing for TTFT, TPS, and Total. tried using them but nothing happens. whereas the other two filter dynamically as expected.

**Comment by juberti** [comment]
yeah, the underlying units are in seconds so you need to put in 0.8 or whatnot to filter out results <= 800 ms. Agree this is far from intuitive, although removing the filter on those columns made the grid look weird. Thoughts?

**Comment by juberti** [comment]
Tweaked the filters to use millisecond units, which now works pretty well. PTAL

**Comment by benlower** [comment]
yeah def better!

**Review by benlower — APPROVED** [review]

**Pull request merged**
